### ISSUE TITLE
Add statistics on used metrics

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#107]
It would be nice to have a 'stats' table that could for example record the 'last_access_time' for a metric. This could have a probability of 10% of being updated and would give us an idea of rarely used metrics.

**Comment by dpanth3r** [comment]
We could store these with a fixed TTL, giving us a table that contains the set of metrics that have been frequently accessed within the last N days.

It would obviously be probabilistic, but we can choose the update probability so that it strikes a balance between overwrite problems and making a frequently-accessed metric not listed rather unlikely.

**Comment by iksaif** [comment]
Yep, good idea, maybe @rveznaver could use that too instead of adding mtime to the existing metric table. (But then we would need a way to remove whatever is not in the intersection of both tables)
