### ISSUE TITLE
Dropping support on biggraphite ? 

### ISSUE THREAD

**Issue by david-guenault** [criteo/biggraphite#566]
Sorry had to create a new issue because i can't answer anymore on #565. @mycroft does that mean you will stop supporting biggraphite ? 

Regards, 
David

**Comment by mycroft** [comment]
I don't know why you can't reply the former thread. If you have more question about this, feel free to mail me at p.marie at criteo dot com.

To answer you: We have no plan nor real resources to maintain it at the maintenance level it was a few years ago. That mostly mean no new feature development. However, we are not throwing yet the project, as there are a lot of projects in the company still using graphite for their metrics, and we plan to keep it until at least end of 2022.

The things we plan at the short/medium term:
* Moving on to drop Python 2 support so we can upgrade dependencies;
* We might work on the backend metadata storage, as we want to stop using cassandra internally & switch to scylladb, but we didn't decide yet which path to take yet as scylladb is not doing SASI indices;
* I have a couple of maintenance related patches still in the pipeline;
* Rebuild the build testing pipeline using Github Actions;
* Still continue to take a look at incoming issues, if possible.

**Comment by mycroft** [comment]
Feel free to mail me if you have any futher question about that!

**Comment by iksaif** [comment]
> * We might work on the backend metadata storage, as we want to stop using cassandra internally & switch to scylladb, but we didn't decide yet which path to take yet as scylladb is not doing SASI indices;

interesting, I always though the cost of maintaining a new kind of DB was higher that most of the optimisations that it brings, good luck with that.

That being said, that's why the ES metadata plugin was made in the first place, it never was fully finished but there is no reason for it not to work.

**Comment by mycroft** [comment]
> interesting, I always though the cost of maintaining a new kind of DB was higher that most of the optimisations that it brings, good luck with that.

Can't argue with that. If it was me, I'd stick with Cassandra at 100% at it works as long as the effort to keep contents & queries in a good shape is made, and this until its EOL.

> That being said, that's why the ES metadata plugin was made in the first place, it never was fully finished but there is no reason for it not to work.

As far as I know, all experiments recently done here (at least the last 2 years) to migrate to ES badly ended due to several reason (mainly too much load, or results inconsistencies). I personally didn't work on that so I can't bring more information about this. However, I might take a new look if I have no further choice in a near future.

**Comment by geobeau** [comment]
To be clearer: ScyllaDB is a drop-in replacement for Cassandra. It will replace the Cassandra cluster for biggraphite_data but its indexing performance for biggraphite_metadata is yet to be determined!
